export const EVENT_TYPES = {
  SESSION_STARTED: "session.started",
  SESSION_RESUMED: "session.resumed",
  SESSION_ENDED: "session.ended",
  SESSION_DELETED: "session.deleted",
  TASK_CREATED: "task.created",
  TASK_STATUS_CHANGED: "task.status_changed",
  TASK_NODE_CREATED: "task_node.created",
  TASK_NODE_DECOMPOSED: "task_node.decomposed",
  TASK_NODE_SELECTED: "task_node.selected",
  TASK_NODE_STARTED: "task_node.started",
  TASK_NODE_COMPLETED: "task_node.completed",
  TASK_NODE_FAILED: "task_node.failed",
  TASK_NODE_PRUNED: "task_node.pruned",
  TURN_STARTED: "turn.started",
  TURN_LINKED_TO_TASK: "turn.linked_to_task",
  TURN_ENDED: "turn.ended",
  TRACE_STARTED: "trace.started",
  TRACE_ENDED: "trace.ended",
  STAGE_TRANSITIONED: "stage.transitioned",
  RESULT_EVALUATED: "result.evaluated",
  CASE_CREATED: "case.created",
  CASE_STATUS_CHANGED: "case.status_changed",
  CASE_REPRODUCTION_RECORDED: "case.reproduction_recorded",
  CASE_SPLIT_CHANGED: "case.split_changed",
  EXPERIENCE_CREATED: "experience.created",
  EXPERIENCE_STATUS_CHANGED: "experience.status_changed",
  RECALL_PERFORMED: "recall.performed",
  RECALL_FEEDBACK_RECORDED: "recall.feedback_recorded",
  SKILL_CREATED: "skill.created",
  SKILL_STATUS_CHANGED: "skill.status_changed",
  VALIDATION_COMPLETED: "validation.completed",
  SKILL_INVOCATION_RECORDED: "skill.invocation_recorded",
} as const;

export type HarnessEventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];
